from __future__ import annotations
import json
from pathlib import Path

import sys

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.stats import friedmanchisquare
from sklearn.decomposition import PCA

sys.path.append(str(Path(__file__).resolve().parents[1]))
from config import CONTROL_PERSONA_ID

ROOT = Path(__file__).resolve().parents[1]
PROC = ROOT / "data" / "processed"
PLOTS = PROC / "plots"
TABLES = ROOT / "paper" / "tables"
TABLES.mkdir(parents=True, exist_ok=True)

CRIT_SHORT = {
    "statement_program_consistency": "Stmt.-program consistency",
    "proposal_specificity": "Proposal specificity",
    "communication_clarity": "Communication clarity",
    "economic_coverage": "Economic coverage",
    "social_coverage": "Social coverage",
    "environmental_coverage": "Environmental coverage",
    "tone_moderation": "Tone moderation",
    "internal_cohesion": "Internal cohesion",
    "positional_stability": "Positional stability",
}
CRIT_ORDER = list(CRIT_SHORT.keys())

MODEL_ORDER = [
    "gemini-3.5-flash", "mistral-medium-3-5", "qwen3.6-27b",
    "llama-3.3-70b-versatile", "gpt-oss-120b-groq",
    "nemotron-3-super-120b-a12b",
]

MODEL_MAP = {
    "gemini-3.5-flash": "gemini-3.5-flash", "mistral-medium-3-5": "mistral-medium-3-5",
    "qwen3.6-27b": "qwen3.6", "llama-3.3-70b-versatile": "llama-3.3",
    "gpt-oss-120b-groq": "gpt-oss", "nemotron-3-super-120b-a12b": "nemotron-3-super",
}

def esc(s: str) -> str:
    return str(s).replace("&", "\\&").replace("_", "\\_").replace("'", "\\textquotesingle{}")


def main() -> None:
    scores = pd.read_csv(PROC / "scores.csv")
    refusal = pd.read_csv(PROC / "refusal_rates.csv")
    corr = pd.read_csv(PROC / "model_correlation.csv", index_col=0)

    if "persona" in scores.columns:
        n_tot = len(scores)
        scores = scores[scores["persona"] == CONTROL_PERSONA_ID].copy()
        print(
            f"Control condition: {len(scores)}/{n_tot} rows "
            f"(persona == '{CONTROL_PERSONA_ID}'); persona rows excluded."
        )

    valid = scores[scores["punteggio"].notna()].copy()
    models = [m for m in MODEL_ORDER if m in scores["model"].unique()]
    stats: dict = {}

    per_model = []
    for m in models:
        sm = scores[scores["model"] == m]
        vm = valid[valid["model"] == m]
        r = refusal[refusal["model"] == m].iloc[0]
        per_model.append({
            "model": MODEL_MAP[m],
            "n_valid": int(vm.shape[0]),
            "mean": vm["punteggio"].mean(),
            "refusal": float(r["tasso_rifiuto"]),
            "api_error": float(r["tasso_errore_api"]),
        })
    pm = pd.DataFrame(per_model)
    stats["per_model"] = pm.to_dict(orient="records")

    lines = [
        "% auto-generated by scripts/generate_paper_assets.py -- do not edit by hand",
        "\\begin{tabular}{lrrrr}", "\\toprule",
        "\\textbf{Model} & \\textbf{Valid} & \\textbf{Mean} & "
        "\\textbf{Refusal} & \\textbf{API err.} \\\\", "\\midrule",
    ]
    for _, row in pm.iterrows():
        lines.append(
            f"{esc(row['model'])} & {row['n_valid']:d} & {row['mean']:.2f} & "
            f"{row['refusal']*100:.1f}\\% & {row['api_error']*100:.1f}\\% \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    (TABLES / "tab_model_reliability.tex").write_text("\n".join(lines))

    pmb = pm.sort_values("refusal", ascending=True)
    fig, ax = plt.subplots(figsize=(8, 4.5))
    bars = ax.barh(pmb["model"], pmb["refusal"] * 100, color="#c0392b")
    for b, v in zip(bars, pmb["refusal"] * 100):
        ax.text(v + 0.2, b.get_y() + b.get_height() / 2, f"{v:.1f}%",
                va="center", fontsize=11)
    ax.set_xlabel("Refusal rate (%)", fontsize=12)
    ax.tick_params(labelsize=11)
    ax.margins(x=0.12)
    fig.tight_layout()
    fig.savefig(PLOTS / "barplot_refusal.pdf", bbox_inches="tight")
    plt.close(fig)

    corr = corr.loc[[m for m in models if m in corr.index],
                    [m for m in models if m in corr.columns]]
    abbr = {m: m.split("-")[0][:6] for m in models}
    lines = [
        "% auto-generated -- do not edit by hand",
        "\\begin{tabular}{l" + "r" * len(corr.columns) + "}", "\\toprule",
        " & " + " & ".join(esc(abbr[c]) for c in corr.columns) + " \\\\", "\\midrule",
    ]
    for idx, r in corr.iterrows():
        cells = " & ".join(f"{v:.2f}" for v in r.values)
        lines.append(f"{esc(abbr[idx])} & {cells} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (TABLES / "tab_model_correlation.tex").write_text("\n".join(lines))
    off = corr.values[~np.eye(len(corr), dtype=bool)]
    stats["corr_mean"] = float(off.mean())
    stats["corr_min"] = float(off.min())
    stats["corr_max"] = float(off.max())

    crit_mean = valid.groupby("criterio")["punteggio"].agg(["mean", "std"])
    crit_mean = crit_mean.reindex(CRIT_ORDER)
    stats["criterion_means"] = {k: float(v) for k, v in crit_mean["mean"].items()}
    lines = [
        "% auto-generated -- do not edit by hand",
        "\\begin{tabular}{lrr}", "\\toprule",
        "\\textbf{Criterion} & \\textbf{Mean} & \\textbf{SD} \\\\", "\\midrule",
    ]
    for cid, r in crit_mean.iterrows():
        lines.append(f"{esc(CRIT_SHORT[cid])} & {r['mean']:.2f} & {r['std']:.2f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (TABLES / "tab_criterion_means.tex").write_text("\n".join(lines))

    cm = crit_mean.sort_values("mean", ascending=True)
    fig, ax = plt.subplots(figsize=(7.2, 4.0))
    ax.barh([CRIT_SHORT[c] for c in cm.index], cm["mean"],
            xerr=cm["std"], color="#4C72B0", edgecolor="none",
            error_kw=dict(ecolor="#333333", capsize=3, lw=1))
    ax.set_xlim(1, 5)
    ax.set_xlabel("Mean score (1-5)")
    ax.axvline(3, color="grey", ls="--", lw=0.8, zorder=0)
    for y, (v, s) in enumerate(zip(cm["mean"], cm["std"])):
        ax.text(v + s + 0.08, y, f"{v:.2f}", va="center", fontsize=8)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.tight_layout()
    fig.savefig(PLOTS / "barplot_criterion_means.pdf")
    plt.close(fig)

    me = valid.groupby(["model", "entity_name"])["punteggio"].mean().reset_index()
    piv = me.pivot(index="entity_name", columns="model", values="punteggio")
    piv = piv[[m for m in models if m in piv.columns]]
    ent_overall = piv.mean(axis=1).sort_values(ascending=False)
    ent_std = piv.std(axis=1)

    ranking = pd.DataFrame({
        "entity": ent_overall.index,
        "mean": ent_overall.values,
        "sd_between_models": ent_std.reindex(ent_overall.index).values,
    })
    etype = valid.drop_duplicates("entity_name").set_index("entity_name")["entity_type"]
    ranking["type"] = ranking["entity"].map(etype)
    stats["entity_ranking"] = ranking.to_dict(orient="records")
    stats["entity_top"] = ranking.iloc[0]["entity"]
    stats["entity_bottom"] = ranking.iloc[-1]["entity"]
    stats["entity_gap"] = float(ranking["mean"].max() - ranking["mean"].min())

    lines = [
        "% auto-generated -- do not edit by hand",
        "\\begin{tabular}{llrr}", "\\toprule",
        "\\textbf{Rank} & \\textbf{Entity} & \\textbf{Mean} & "
        "\\textbf{SD$_{\\text{models}}$} \\\\", "\\midrule",
    ]
    for i, (_, r) in enumerate(ranking.iterrows(), 1):
        tag = "P" if r["type"] == "partito" else "L"
        lines.append(
            f"{i} & {esc(r['entity'])} ({tag}) & {r['mean']:.2f} & "
            f"{r['sd_between_models']:.2f} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    (TABLES / "tab_entity_ranking.tex").write_text("\n".join(lines))

    common = piv.dropna(axis=0, how="any")
    ranks = common.rank(ascending=False)
    n, k = ranks.shape
    Rj = ranks.sum(axis=1)
    S = ((Rj - Rj.mean()) ** 2).sum()
    W = 12 * S / (k ** 2 * (n ** 3 - n))
    stats["kendall_w"] = float(W)
    stats["kendall_w_n_entities"] = int(n)
    stats["kendall_w_k_models"] = int(k)
    try:
        chi, p = friedmanchisquare(*[common.loc[e].values for e in common.index])
        stats["friedman_chi2"] = float(chi)
        stats["friedman_p"] = float(p)
        stats["friedman_df"] = int(n - 1)
    except Exception as e:
        stats["friedman_error"] = str(e)
    from scipy.stats import spearmanr
    cols = list(common.columns)
    rhos = []
    for a in range(len(cols)):
        for b in range(a + 1, len(cols)):
            rho, _ = spearmanr(common[cols[a]], common[cols[b]])
            rhos.append(rho)
    stats["spearman_mean"] = float(np.mean(rhos))
    stats["spearman_min"] = float(np.min(rhos))
    stats["spearman_max"] = float(np.max(rhos))

    hp = piv.reindex(ent_overall.index)
    fig, ax = plt.subplots(figsize=(9.5, 11))
    im = ax.imshow(hp.values, aspect="auto", cmap="viridis", vmin=1, vmax=5)
    ax.set_xticks(range(len(hp.columns)))
    ax.set_xticklabels([MODEL_MAP[m] for m in hp.columns], rotation=40, ha="right", fontsize=12)
    ax.set_yticks(range(len(hp.index)))
    ax.set_yticklabels(hp.index, fontsize=12)
    for i in range(hp.shape[0]):
        for j in range(hp.shape[1]):
            v = hp.values[i, j]
            if not np.isnan(v):
                col = "white" if v < 3.4 else "black"
                ax.text(j, i, f"{v:.1f}", ha="center", va="center",
                        fontsize=10, color=col)
    cb = fig.colorbar(im, ax=ax, shrink=0.5, label="Mean score (1-5)")
    cb.ax.yaxis.label.set_size(13)
    cb.ax.tick_params(labelsize=11)
    ax.set_title("Mean rubric score by model and entity", fontsize=15)
    fig.tight_layout()
    fig.savefig(PLOTS / "heatmap_model_entity.pdf", bbox_inches="tight")
    plt.close(fig)

    RADAR_ENTITY = "Fratelli d'Italia"
    rad = (valid[valid["entity_name"] == RADAR_ENTITY]
           .groupby(["model", "criterio"])["punteggio"].mean().reset_index())
    rmat = rad.pivot(index="model", columns="criterio", values="punteggio")
    rmat = rmat.reindex(index=[m for m in models if m in rmat.index],
                        columns=CRIT_ORDER)
    short_axis = {
        "statement_program_consistency": "Stmt.-program\nconsistency",
        "proposal_specificity": "Proposal\nspecificity",
        "communication_clarity": "Communication\nclarity",
        "economic_coverage": "Economic\ncoverage",
        "social_coverage": "Social\ncoverage",
        "environmental_coverage": "Environmental\ncoverage",
        "tone_moderation": "Tone\nmoderation",
        "internal_cohesion": "Internal\ncohesion",
        "positional_stability": "Positional\nstability",
    }
    labels = [short_axis[c] for c in CRIT_ORDER]
    ang = np.linspace(0, 2 * np.pi, len(CRIT_ORDER), endpoint=False)
    ang_closed = np.concatenate([ang, ang[:1]])
    fig, ax = plt.subplots(figsize=(9, 9), subplot_kw=dict(polar=True))
    cmap = plt.get_cmap("tab10")
    for i, m in enumerate(rmat.index):
        vals = rmat.loc[m].values
        vals = np.concatenate([vals, vals[:1]])
        ax.plot(ang_closed, vals, linewidth=2, color=cmap(i), label=m)
        ax.fill(ang_closed, vals, color=cmap(i), alpha=0.06)
    ax.set_xticks(ang)
    ax.set_xticklabels(labels, fontsize=12)
    ax.set_ylim(1, 5)
    ax.set_yticks([1, 2, 3, 4, 5])
    ax.set_yticklabels(["1", "2", "3", "4", "5"], fontsize=11)
    ax.set_rlabel_position(0)
    ax.tick_params(axis="x", pad=18)
    ax.set_title(f"{RADAR_ENTITY}: mean score per criterion by model",
                 fontsize=15, pad=28)
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.08), ncol=3,
              fontsize=10, frameon=True)
    fig.tight_layout()
    fig.savefig(PLOTS / "radar_paper_FdI.pdf", bbox_inches="tight")
    plt.close(fig)

    def stars(p: float) -> str:
        return ("$^{***}$" if p < 1e-3 else "$^{**}$" if p < 1e-2
                else "$^{*}$" if p < 5e-2 else "")
    lines = [
        "% auto-generated -- do not edit by hand",
        "\\begin{tabular}{lr}", "\\toprule",
        "\\textbf{Agreement statistic} & \\textbf{Value} \\\\", "\\midrule",
        f"Kendall's $W$ (concordance) & {W:.2f} \\\\",
        (f"Friedman $\\chi^2$ (df$=${n-1}) & "
         f"{stats['friedman_chi2']:.1f}{stars(stats['friedman_p'])} \\\\"),
        f"Mean pairwise Spearman $\\rho$ & {stats['spearman_mean']:.2f} \\\\",
        f"\\quad range & [{stats['spearman_min']:.2f}, {stats['spearman_max']:.2f}] \\\\",
        f"Mean pairwise Pearson (profiles) & {stats['corr_mean']:.2f} \\\\",
        "\\bottomrule", "\\end{tabular}",
    ]
    (TABLES / "tab_agreement.tex").write_text("\n".join(lines))

    prof = (valid.groupby(["model", "entity_name", "criterio"])["punteggio"]
            .mean().reset_index())
    prof["cell"] = prof["entity_name"] + "|" + prof["criterio"]
    mat = prof.pivot(index="model", columns="cell", values="punteggio")
    mat = mat.reindex([m for m in models if m in mat.index])
    mat = mat.dropna(axis=1, how="any")
    X = mat.values
    Xc = X - X.mean(axis=0)
    pca = PCA(n_components=2)
    Y = pca.fit_transform(Xc)
    stats["pca_explained"] = [float(v) for v in pca.explained_variance_ratio_]
    stats["pca_n_cells"] = int(mat.shape[1])

    fig, ax = plt.subplots(figsize=(7, 6))
    ax.scatter(Y[:, 0], Y[:, 1], s=60, color="#333")
    for (name, x, y) in zip(mat.index, Y[:, 0], Y[:, 1]):
        ax.annotate(name, (x, y), fontsize=8, xytext=(5, 3),
                    textcoords="offset points")
    ax.set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.0f}%)")
    ax.set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.0f}%)")
    ax.set_title("PCA of model judgment profiles")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(PLOTS / "pca_models.pdf")
    plt.close(fig)

    for ent in ["Futuro Nazionale", "Roberto Vannacci"]:
        sub = scores[scores["entity_name"] == ent]
        if len(sub):
            stats.setdefault("post_cutoff", {})[ent] = {
                "null_rate": float(sub["punteggio"].isna().mean()),
                "refusal_rate": float(sub["rifiuto_o_non_parsabile"].mean()),
            }

    cellv = (valid.groupby(["model", "entity_name", "criterio", "prompt_variant"])
             ["punteggio"].mean().reset_index())
    wide = cellv.pivot_table(index=["model", "entity_name", "criterio"],
                             columns="prompt_variant", values="punteggio")
    wide = wide.dropna(subset=["v1", "v2"])
    delta = (wide["v1"] - wide["v2"]).abs()
    from scipy.stats import pearsonr
    r_var, _ = pearsonr(wide["v1"], wide["v2"])
    stats["variant"] = {
        "mae": float(delta.mean()),
        "pearson": float(r_var),
        "frac_delta_ge_1": float((delta >= 1).mean()),
        "n_cells": int(len(wide)),
    }
    ref_by_var = (scores.groupby("prompt_variant")["rifiuto_o_non_parsabile"]
                  .mean().to_dict())
    stats["variant"]["refusal_v1"] = float(ref_by_var.get("v1", float("nan")))
    stats["variant"]["refusal_v2"] = float(ref_by_var.get("v2", float("nan")))

    rows = []
    for m in models:
        w = wide.reset_index()
        w = w[w["model"] == m]
        sm = scores[scores["model"] == m]
        r1 = sm[sm["prompt_variant"] == "v1"]["rifiuto_o_non_parsabile"].mean()
        r2 = sm[sm["prompt_variant"] == "v2"]["rifiuto_o_non_parsabile"].mean()
        rows.append({
            "model": m, "mean_v1": w["v1"].mean(), "mean_v2": w["v2"].mean(),
            "mae": (w["v1"] - w["v2"]).abs().mean(),
            "ref_v1": r1, "ref_v2": r2,
        })
    stats["variant"]["per_model"] = rows
    lines = [
        "% auto-generated -- do not edit by hand",
        "\\begin{tabular}{lrrrrr}", "\\toprule",
        "\\textbf{Model} & \\textbf{Mean v1} & \\textbf{Mean v2} & "
        "\\textbf{MAE} & \\textbf{Ref. v1} & \\textbf{Ref. v2} \\\\", "\\midrule",
    ]
    for r in rows:
        lines.append(
            f"{esc(r['model'])} & {r['mean_v1']:.2f} & {r['mean_v2']:.2f} & "
            f"{r['mae']:.2f} & {r['ref_v1']*100:.1f}\\% & {r['ref_v2']*100:.1f}\\% \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    (TABLES / "tab_variant_sensitivity.tex").write_text("\n".join(lines))

    write_persona_tables()

    write_winner_table()
    write_positional_table()

    (PROC / "paper_stats.json").write_text(json.dumps(stats, indent=2, default=str))
    print("Tables written to", TABLES)
    print("Figure: heatmap_model_entity.pdf, pca_models.pdf")
    print(json.dumps(stats, indent=2, default=str))


PERSONA_LABEL = {
    "left": "Left", "center_left": "Centre-left", "center": "Centre",
    "center_right": "Centre-right", "right": "Right",
}
PERSONA_ORDER = ["left", "center_left", "center", "center_right", "right"]


def _stars(p: float) -> str:
    return "$^{***}$" if p < 0.001 else "$^{**}$" if p < 0.01 else "$^{*}$" if p < 0.05 else ""


def write_persona_tables() -> None:
    tests_p = PROC / "persona_tests.csv"
    slope_p = PROC / "persona_entity_slope.csv"
    if not (tests_p.exists() and slope_p.exists()):
        print("Persona tables skipped: run scripts/analyze_personas.py first.")
        return

    t = pd.read_csv(tests_p).set_index("persona").reindex(PERSONA_ORDER)
    lines = [
        "% auto-generated -- do not edit by hand",
        "\\begin{tabular}{lrr}", "\\toprule",
        "\\textbf{Persona} & \\textbf{Mean shift} & \\textbf{$\\Delta$SD} \\\\",
        "\\midrule",
    ]
    for pid, r in t.iterrows():
        lines.append(
            f"{PERSONA_LABEL[pid]} & {r['shift_mean']:+.2f} & "
            f"{r['delta_std_mean']:+.3f} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    (TABLES / "tab_persona_effect.tex").write_text("\n".join(lines))

    s = pd.read_csv(slope_p).sort_values("slope")
    lines = [
        "% auto-generated -- do not edit by hand",
        "\\begin{tabular}{lrrr}", "\\toprule",
        "\\textbf{Entity} & \\textbf{Slope} & \\textbf{95\\% CI} & \\textbf{$R^2$} \\\\",
        "\\midrule",
    ]
    for _, r in s.iterrows():
        lines.append(
            f"{esc(r['entity_name'])} & {r['slope']:+.3f}{_stars(r['p_bh'])} & "
            f"[{r['ci_low']:+.3f}, {r['ci_high']:+.3f}] & {r['r2']:.2f} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    (TABLES / "tab_persona_slope.tex").write_text("\n".join(lines))
    print("Wrote tab_persona_effect.tex and tab_persona_slope.tex")


def write_winner_table() -> None:
    agree_p = PROC / "criterion_winner_agreement.csv"
    if not agree_p.exists():
        print("Winners table skipped: run scripts/criterion_winners.py first.")
        return

    a = pd.read_csv(agree_p)
    parties = a[a["entity_type"] == "partito"].set_index("criterio")
    leaders = a[a["entity_type"] == "leader"].set_index("criterio")

    lines = [
        "% auto-generated -- do not edit by hand",
        "\\begin{tabular}{lllll}", "\\toprule",
        "& \\multicolumn{2}{c}{\\textbf{Parties}} & "
        "\\multicolumn{2}{c}{\\textbf{Leaders}} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
        "\\textbf{Criterion} & \\textbf{Top-ranked} & \\textbf{Models} & "
        "\\textbf{Top-ranked} & \\textbf{Models} \\\\", "\\midrule",
    ]
    for c in CRIT_ORDER:
        cells = []
        for tab in (parties, leaders):
            if c in tab.index:
                r = tab.loc[c]
                raw = r["top_entity"]
                if not isinstance(raw, str):
                    cells += ["---", "---"]
                    continue
                name = ", ".join(esc(x) for x in raw.split("|"))
                frac = f"{int(r['n_models_first'])}/{int(r['n_models'])}"
                if bool(r["unanimous"]):
                    name = f"\\textbf{{{name}}}"
                cells += [name, frac]
            else:
                cells += ["---", "---"]
        lines.append(f"{CRIT_SHORT[c]} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (TABLES / "tab_criterion_winners.tex").write_text("\n".join(lines))
    print("Wrote tab_criterion_winners.tex")


def write_positional_table() -> None:
    p = PROC / "criterion_positional_winners.csv"
    if not p.exists():
        print("Positional table skipped: run scripts/criterion_winners.py first.")
        return

    a = pd.read_csv(p)
    parties = a[a["entity_type"] == "partito"].set_index("criterio")
    leaders = a[a["entity_type"] == "leader"].set_index("criterio")

    lines = [
        "% auto-generated -- do not edit by hand",
        "\\begin{tabular}{lllll}", "\\toprule",
        "& \\multicolumn{2}{c}{\\textbf{Parties}} & "
        "\\multicolumn{2}{c}{\\textbf{Leaders}} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
        "\\textbf{Criterion} & \\textbf{Top-ranked} & \\textbf{Score (gap)} & "
        "\\textbf{Top-ranked} & \\textbf{Score (gap)} \\\\", "\\midrule",
    ]
    for c in CRIT_ORDER:
        cells = []
        for tab in (parties, leaders):
            if c not in tab.index:
                cells += ["---", "---"]
                continue
            r = tab.loc[c]
            raw = r["top_entity"]
            if not isinstance(raw, str):
                cells += ["---", "---"]
                continue
            name = ", ".join(esc(x) for x in raw.split("|"))
            score = float(r["pos_score"])
            gap = float(r["gap"])
            if score >= 1.0 - 1e-9:
                name = f"\\textbf{{{name}}}"
            cells += [name, f"{score:.2f} ({gap:+.2f})"]
        lines.append(f"{CRIT_SHORT[c]} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (TABLES / "tab_criterion_positional.tex").write_text("\n".join(lines))
    print("Wrote tab_criterion_positional.tex")


if __name__ == "__main__":
    main()
